{{- if .Values.demo.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.demo.credentialsSecret }}
  namespace: {{ .Values.demo.namespace }}
type: Opaque
stringData:
  apitoken: {{ .Values.litemaas.apiKey }}
{{- end }}