# Use RHEL UBI 9
FROM registry.access.redhat.com/ubi9/ubi:latest

# Install openssh-clients
RUN yum install -y openssh-clients && \
    yum clean all

RUN yum install -y yum-utils
RUN yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
RUN yum -y install vault

RUN chgrp -R 0 /usr/bin/vault && \
    chmod -R g=u /usr/bin/vault

# Keep container running to allow exec
CMD ["/bin/bash", "-c", "--", "ssh-keygen -q -t rsa -N '' -f /tmp/id_rsa; while true; do sleep 30; done;"]